# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'

# Services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service always from latest-tagged image
    image: healthmonitoringapi:latest
    ports:
      - "8080:8080"
    restart: always  
    links:
      - db # Linking to the database service
    environment:
      DATABASE: db

  db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ~/docker/postgresql/postgres/data:/var/lib/postgresql/data